### ISSUE TITLE
python 3.4?

### ISSUE THREAD

**Issue by Serpens66** [slazarov/python-signalr-client#1]
Hi, thank you very much for this. I don't like the "wait" thing with the other signalR module, so I think async is a nice solution.
Unfortunately I still use python 3.4 and don't want to update.

So can I simply replace:
1) "async def..." with
"@asyncio.coroutine
def ..."

2) "await" with "yield from"

3) "async with session.get(url) as r:"  with "r = yield from session.get(url)"

and everything is fine? Or is it more complex?

edit:
Just saw you also use "async for".. I found no short alternative for this, just a big block of code in last example of response here: https://stackoverflow.com/questions/34338518/async-for-in-python-3-4

**Comment by slazarov** [comment]
I haven't used asyncio before py3.5 but from what I read this should suffice. I recommend either reading about what changes were made and reverse them or the better solution: update to py3.5.
