### ISSUE TITLE
A new release with support for Python 3.10

### ISSUE THREAD

**Issue by oscr** [slazarov/python-signalr-client#22]
Hi @slazarov! 

First of thank you for this great library. It's really helpful. 

I've experimented a little to get the project ready for Python 3.10 in order to use it for (Fast-F1)[https://github.com/theOehrly/Fast-F1]. It seems like it could be pretty straight forward: https://github.com/oscr/python-signalr-client/commit/45edbc4d1004372f92f5dec590abc076b63e6853

How would you feel about making a new release with Python 3.10 support?

EDIT: I can make a pr for it just to be clear.

**Comment by slazarov** [comment]
Hi @oscr, I am not active on github currently and I do not maintain my libraries so I cannot offer any support.

**Comment by oscr** [comment]
@slazarov Thank you for the quick reply! It's much appreciated. 

If you're not active it is possible to archive repos in Github (I have archived some of my not active projects) to indicate this and avoid getting questions like this: https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories
