### ISSUE TITLE
      done pending?

### ISSUE THREAD

**Issue by purplecity** [slazarov/python-signalr-client#9]
hi at transport.py  line 69  

<img width="707" alt="wechatimg6" src="https://user-images.githubusercontent.com/38914615/44707581-75739600-aad7-11e8-820d-c77b317d7f16.png">

I am new about asyncio,I don't  know why asyncio.gather will return a done and pending fs.  done and pending fs  return by call asyncio.wait function at python documention

<img width="682" alt="wechatimg7" src="https://user-images.githubusercontent.com/38914615/44707585-799fb380-aad7-11e8-9dd8-c6fec5b79402.png">

**Comment by slazarov** [comment]
Nicely spotted, fixed.
https://github.com/slazarov/python-signalr-client/commit/534ecc4b59f3beb2846ca37f7b4a2cf9dc9015e7

**Comment by slazarov** [comment]
Well spot, fixed.
https://github.com/slazarov/python-signalr-client/commit/534ecc4b59f3beb2846ca37f7b4a2cf9dc9015e7
